[build]
  command = "npm run build"
  publish = "dist"
  # functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }


[dev]
  command = "npm run start"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  # functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
